name: Update RunnTV EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test downloader
        run: |
          python -m src.main

      - name: Upload response
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-response
          path: response.bin